### ISSUE TITLE
JDC ax6600  the router does not turn on,

### ISSUE THREAD

**Issue by Doanduy09** [VIKINGYFY/OpenWRT-CI#91]
I have built and flashed the ROM but there is no signal, the router does not turn on, please help me fix it

**Comment by VIKINGYFY** [comment]
We already know the problem. It will be fixed soon.

**Comment by Doanduy09** [comment]
thanks you

**Comment by VIKINGYFY** [comment]
It should be fixed now. You can try it.

**Comment by Doanduy09** [comment]
jdc ax6600, I built it successfully but usb still not working

**Comment by VIKINGYFY** [comment]
https://github.com/lgs2007m/Actions-OpenWrt/releases/tag/Router-Flashing-Files

please switch uboot and gpt to this project.

**Comment by Doanduy09** [comment]
I hope you can help me fix the usb error because I really like your github... very intuitive and beautiful.... thank you

**Comment by Doanduy09** [comment]
thank you i rebuilt it and it worked, the usb worked perfectly, have a nice day
